package com.pachimari.lolapp

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val recyclerView = findViewById<RecyclerView>(R.id.recyclerView)

        val champions = listOf(
            Champion("Aatrox", R.drawable.ch_aatrox),
            Champion("Ahri", R.drawable.ch_ahri),
            Champion("Akali", R.drawable.ch_akali),
            Champion("Alistar", R.drawable.ch_alistar),
            Champion("Amumu", R.drawable.ch_amumu),
            Champion("Anivia", R.drawable.ch_anivia),
            Champion("Annie", R.drawable.ch_annie),
            Champion("Aphelios", R.drawable.ch_aphelios),
            Champion("Ashe", R.drawable.ch_ashe),
            Champion("Aurelion Sol", R.drawable.ch_aurelionsol),
            Champion("Azir", R.drawable.ch_azir),
            Champion("Bard", R.drawable.ch_bard),
            Champion("Blitzcrank", R.drawable.ch_blitzcrank),
            Champion("Brand", R.drawable.ch_brand),
            Champion("Braum", R.drawable.ch_braum),
            Champion("Caitlyn", R.drawable.ch_caitlyn),
            Champion("Camille", R.drawable.ch_camille),
            Champion("Cassiopeia", R.drawable.ch_cassiopeia),
            Champion("Cho'Gath", R.drawable.ch_chogath),
            Champion("Corki", R.drawable.ch_corki),
            Champion("Darius", R.drawable.ch_darius),
            Champion("Diana", R.drawable.ch_diana),
            Champion("Draven", R.drawable.ch_draven),
            Champion("Dr. Mundo", R.drawable.ch_drmundo),
            Champion("Ekko", R.drawable.ch_ekko),
            Champion("Elise", R.drawable.ch_elise),
            Champion("Evelynn", R.drawable.ch_evelynn),
            Champion("Ezreal", R.drawable.ch_ezreal),
            Champion("Fiddlesticks", R.drawable.ch_fiddlesticks),
            Champion("Fiora", R.drawable.ch_fiora),
            Champion("Fizz", R.drawable.ch_fizz),
            Champion("Galio", R.drawable.ch_galio),
            Champion("Gangplank", R.drawable.ch_gangplank),
            Champion("Garen", R.drawable.ch_garen),
            Champion("Gnar", R.drawable.ch_gnar),
            Champion("Gragas", R.drawable.ch_gragas),
            Champion("Graves", R.drawable.ch_graves),
            Champion("Hecarim", R.drawable.ch_hecarim),
            Champion("Heimerdinger", R.drawable.ch_heimerdinger),
            Champion("Illaoi", R.drawable.ch_illaoi),
            Champion("Irelia", R.drawable.ch_irelia),
            Champion("Ivern", R.drawable.ch_ivern),
            Champion("Janna", R.drawable.ch_janna),
            Champion("Jarvan IV", R.drawable.ch_jarvaniv),
            Champion("Jax", R.drawable.ch_jax),
            Champion("Jayce", R.drawable.ch_jayce),
            Champion("Jhin", R.drawable.ch_jhin),
            Champion("Jinx", R.drawable.ch_jinx),
            Champion("Kai'Sa", R.drawable.ch_kaisa),
            Champion("Kalista", R.drawable.ch_kalista),
            Champion("Karma", R.drawable.ch_karma),
            Champion("Karthus", R.drawable.ch_karthus),
            Champion("Kassadin", R.drawable.ch_kassadin),
            Champion("Katarina", R.drawable.ch_katarina),
            Champion("Kayle", R.drawable.ch_kayle),
            Champion("Kayn", R.drawable.ch_kayn),
            Champion("Kennen", R.drawable.ch_kennen),
            Champion("Kha'Zix", R.drawable.ch_khazix),
            Champion("Kindred", R.drawable.ch_kindred),
            Champion("Kled", R.drawable.ch_kled),
            Champion("Kog'Maw", R.drawable.ch_kogmaw),
            Champion("LeBlanc", R.drawable.ch_leblanc),
            Champion("Lee Sin", R.drawable.ch_leesin),
            Champion("Leona", R.drawable.ch_leona),
            Champion("Lillia", R.drawable.ch_lillia),
            Champion("Lissandra", R.drawable.ch_lissandra),
            Champion("Lucian", R.drawable.ch_lucian),
            Champion("Lulu", R.drawable.ch_lulu),
            Champion("Lux", R.drawable.ch_lux),
            Champion("Malphite", R.drawable.ch_malphite),
            Champion("Malzahar", R.drawable.ch_malzahar),
            Champion("Maokai", R.drawable.ch_maokai),
            Champion("Master Yi", R.drawable.ch_masteryi),
            Champion("Miss Fortune", R.drawable.ch_missfortune),
            Champion("Mordekaiser", R.drawable.ch_mordekaiser),
            Champion("Morgana", R.drawable.ch_morgana),
            Champion("Nami", R.drawable.ch_nami),
            Champion("Nasus", R.drawable.ch_nasus),
            Champion("Nautilus", R.drawable.ch_nautilus),
            Champion("Neeko", R.drawable.ch_neeko),
            Champion("Nidalee", R.drawable.ch_nidalee),
            Champion("Nocturne", R.drawable.ch_nocturne),
            Champion("Nunu & Willump", R.drawable.ch_nunuandwillump),
            Champion("Olaf", R.drawable.ch_olaf),
            Champion("Pyke", R.drawable.ch_pyke),
            Champion("Qiyana", R.drawable.ch_qiyana),
            Champion("Quinn", R.drawable.ch_quinn),
            Champion("Rakan", R.drawable.ch_rakan),
            Champion("Rammus", R.drawable.ch_rammus),
            Champion("Rek'Sai", R.drawable.ch_reksai),
            Champion("Renekton", R.drawable.ch_renekton),
            Champion("Rengar", R.drawable.ch_rengar),
            Champion("Riven", R.drawable.ch_riven),
            Champion("Rumble", R.drawable.ch_rumble),
            Champion("Ryze", R.drawable.ch_ryze),
            Champion("Samira", R.drawable.ch_samira),
            Champion("Sejuani", R.drawable.ch_sejuani),
            Champion("Senna", R.drawable.ch_senna),
            Champion("Sett", R.drawable.ch_sett),
            Champion("Shaco", R.drawable.ch_shaco),
            Champion("Shen", R.drawable.ch_shen),
            Champion("Shyvana", R.drawable.ch_shyvana),
            Champion("Singed", R.drawable.ch_singed),
            Champion("Sion", R.drawable.ch_sion),
            Champion("Sivir", R.drawable.ch_sivir),
            Champion("Skarner", R.drawable.ch_skarner),
            Champion("Sona", R.drawable.ch_sona),
            Champion("Soraka", R.drawable.ch_soraka),
            Champion("Swain", R.drawable.ch_swain),
            Champion("Sylas", R.drawable.ch_sylas),
            Champion("Syndra", R.drawable.ch_syndra),
            Champion("Tahm Kench", R.drawable.ch_tahmkench),
            Champion("Taliyah", R.drawable.ch_taliyah),
            Champion("Talon", R.drawable.ch_talon),
            Champion("Taric", R.drawable.ch_taric),
            Champion("Teemo", R.drawable.ch_teemo),
            Champion("Thresh", R.drawable.ch_thresh),
            Champion("Tristana", R.drawable.ch_tristana),
            Champion("Trundle", R.drawable.ch_trundle),
            Champion("Tryndamere", R.drawable.ch_tryndamere),
            Champion("Twisted Fate", R.drawable.ch_twistedfate),
            Champion("Twitch", R.drawable.ch_twitch),
            Champion("Udyr", R.drawable.ch_udyr),
            Champion("Urgot", R.drawable.ch_urgot),
            Champion("Varus", R.drawable.ch_varus),
            Champion("Vayne", R.drawable.ch_vayne),
            Champion("Veigar", R.drawable.ch_veigar),
            Champion("Vel'Koz", R.drawable.ch_velkoz),
            Champion("Vi", R.drawable.ch_vi),
            Champion("Viktor", R.drawable.ch_viktor),
            Champion("Vladimir", R.drawable.ch_vladimir),
            Champion("Volibear", R.drawable.ch_volibear),
            Champion("Warwick", R.drawable.ch_warwick),
            Champion("Wukong", R.drawable.ch_wukong),
            Champion("Xayah", R.drawable.ch_xayah),
            Champion("Xerath", R.drawable.ch_xerath),
            Champion("Xin Zhao", R.drawable.ch_xinzhao),
            Champion("Yasuo", R.drawable.ch_yasuo),
            Champion("Yone", R.drawable.ch_yone),
            Champion("Yorick", R.drawable.ch_yorick),
            Champion("Yuumi", R.drawable.ch_yuumi),
            Champion("Zac", R.drawable.ch_zac),
            Champion("Zed", R.drawable.ch_zed),
            Champion("Ziggs", R.drawable.ch_ziggs),
            Champion("Zilean", R.drawable.ch_zilean),
            Champion("Zoe", R.drawable.ch_zoe),
            Champion("Zyra", R.drawable.ch_zyra),

        )

        recyclerView.apply {
            layoutManager = GridLayoutManager(this.context, 4)
            adapter = ChampionAdapter(champions)
        }

    }

}

